
name: 'dbt_external_tables_integration_tests'
version: '1.0'

profile: 'integration_tests'

# require-dbt-version: inherit this from package

config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  dbt_external_tables_dispatch_list: ['dbt_external_tables_integration_tests']

sources:
  dbt_external_tables_integration_tests:
    plugins:
      redshift_external:
        +enabled: "{{ target.type == 'redshift' }}"
      snowflake_external:
        +enabled: "{{ target.type == 'snowflake' }}"
      bigquery_external:
        +enabled: "{{ target.type == 'bigquery' }}"
      spark_external:
        +enabled: "{{ target.type == 'spark' }}"
      synapse_external:
        +enabled: "{{ target.type == 'synapse' }}"
      azuresql_external:
        +enabled: "{{ target.type == 'azuresql' }}"

seeds:
  quote_columns: false
